"""initial migration

Revision ID: 14ebd55e7469
Revises: 0e896193e05b
Create Date: 2026-02-20 08:54:05.907908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# リビジョン識別子（Alembic が自動管理）
revision: str = '14ebd55e7469'
down_revision: Union[str, None] = '0e896193e05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """マイグレーション: アップグレード（スキーマ変更の適用）"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """マイグレーション: ダウングレード（スキーマ変更のロールバック）"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
